//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntwerpRC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.Calendar = new HashSet<Calendar>();
            this.Game = new HashSet<Game>();
        }
    
        public long AddressId { get; set; }
        public string Street { get; set; }
        public string Nr { get; set; }
        public string Postalcode { get; set; }
        public string City { get; set; }
        public Nullable<long> CountryId { get; set; }
        public bool AuditDeleted { get; set; }
        public string AuditCreatedBy { get; set; }
        public System.DateTime AuditCreatedOn { get; set; }
        public string AuditModifiedBy { get; set; }
        public Nullable<System.DateTime> AuditModifiedOn { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<decimal> Lattitude { get; set; }
        public long ClubId { get; set; }
        public string Description { get; set; }
    
        public virtual Club Club { get; set; }
        public virtual Country Country { get; set; }
        public virtual ICollection<Calendar> Calendar { get; set; }
        public virtual ICollection<Game> Game { get; set; }
    }
}
