//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntwerpRC.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CalendarEntities : DbContext
    {
        public CalendarEntities()
            : base("name=CalendarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Address> Address { get; set; }
        public DbSet<CalenderItems> CalenderItems { get; set; }
        public DbSet<Categories> Categories { get; set; }
        public DbSet<CategoryTeams> CategoryTeams { get; set; }
        public DbSet<Countries> Countries { get; set; }
        public DbSet<Seasons> Seasons { get; set; }
        public DbSet<TeamAddresses> TeamAddresses { get; set; }
        public DbSet<Teams> Teams { get; set; }
    }
}
