//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntwerpRC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalenderItems
    {
        public long CalenderItemId { get; set; }
        public long CategoryId { get; set; }
        public Nullable<long> SeasonId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public bool FullDays { get; set; }
        public Nullable<long> HomeTeamId { get; set; }
        public string HomeTeamDescription { get; set; }
        public Nullable<long> AwayTeamId { get; set; }
        public string AwayTeamDescription { get; set; }
        public bool Cancelled { get; set; }
        public string CancellationReason { get; set; }
        public bool VisibleForPublic { get; set; }
        public bool AuditDeleted { get; set; }
        public int AuditCreatedBy { get; set; }
        public System.DateTime AuditCreatedOn { get; set; }
        public Nullable<int> AuditModifiedBy { get; set; }
        public Nullable<System.DateTime> AuditModifiedOn { get; set; }
        public Nullable<long> HomeTeamAddressId { get; set; }
        public Nullable<long> AwayTeamAddressId { get; set; }
    
        public virtual Address AwayAddress { get; set; }
        public virtual Address HomeAddress { get; set; }
        public virtual Teams AwayTeam { get; set; }
        public virtual Categories Categories { get; set; }
        public virtual Teams HomeTeam { get; set; }
        public virtual Seasons Seasons { get; set; }
    }
}
