//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntwerpRC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calendar
    {
        public long CalenderId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Descripton { get; set; }
        public bool Cancelled { get; set; }
        public string CancellationReason { get; set; }
        public bool Postponed { get; set; }
        public string PostponedReason { get; set; }
        public Nullable<System.DateTime> PostPOndedDate { get; set; }
        public Nullable<long> GameId { get; set; }
        public Nullable<long> LocationClubAddressId { get; set; }
        public string LocationManual { get; set; }
        public bool PublicEvent { get; set; }
        public bool FullDay { get; set; }
        public bool AuditDeleted { get; set; }
        public string AuditCreatedBy { get; set; }
        public System.DateTime AuditCreatedOn { get; set; }
        public string AuditModifiedBy { get; set; }
        public Nullable<System.DateTime> AuditModifiedOn { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Game Game { get; set; }
    }
}
