//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntwerpRC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public Game()
        {
            this.Calendar = new HashSet<Calendar>();
        }
    
        public long GameId { get; set; }
        public System.DateTime Date { get; set; }
        public long TeamClub1Id { get; set; }
        public Nullable<int> TeamClub1Score { get; set; }
        public Nullable<int> TeamClub1Tries { get; set; }
        public long TeamClub2Id { get; set; }
        public Nullable<int> TeamClub2Score { get; set; }
        public Nullable<int> TeamClub2Tries { get; set; }
        public string GameNumber { get; set; }
        public bool AuditDeleted { get; set; }
        public string AuditCreatedBy { get; set; }
        public System.DateTime AuditCreatedOn { get; set; }
        public string AuditModifiedBy { get; set; }
        public Nullable<System.DateTime> AuditModifiedOn { get; set; }
        public long TeamClub1AddressId { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual ICollection<Calendar> Calendar { get; set; }
        public virtual TeamClub TeamClub { get; set; }
        public virtual TeamClub TeamClub1 { get; set; }
    }
}
