//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntwerpRC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScoreTableLine
    {
        public long TableLineId { get; set; }
        public long TableId { get; set; }
        public int Points { get; set; }
        public int Bonus { get; set; }
        public int TotalPoints { get; set; }
        public int Games { get; set; }
        public int Won { get; set; }
        public int Draw { get; set; }
        public int Lost { get; set; }
        public int Forfait { get; set; }
        public int PositivePoints { get; set; }
        public int NegativePoints { get; set; }
        public int RedCards { get; set; }
        public bool AuditDeleted { get; set; }
        public string AuditCreatedBy { get; set; }
        public System.DateTime AuditCreatedOn { get; set; }
        public string AuditModifiedBy { get; set; }
        public Nullable<System.DateTime> AuditModifiedOn { get; set; }
        public long TeamclubId { get; set; }
        public int Order { get; set; }
        public int InternalOrder { get; set; }
    
        public virtual ScoreTable ScoreTable { get; set; }
        public virtual TeamClub TeamClub { get; set; }
    }
}
