//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntwerpRC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamAddresses
    {
        public long TeamAddressId { get; set; }
        public long TeamId { get; set; }
        public long AddressId { get; set; }
        public bool AuditDeleted { get; set; }
        public int AuditCreatedBy { get; set; }
        public System.DateTime AuditCreatedOn { get; set; }
        public Nullable<int> AuditModifiedBy { get; set; }
        public Nullable<System.DateTime> AuditModifiedOn { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Teams Teams { get; set; }
    }
}
